### ISSUE TITLE
make whole tutorials printable to pdf 

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrilearnr#10]
To provide a backup option for learners with a poor internet connection we'd like to be able to email them a pdf of the tutorial.

We'd like a solution where we can easily generate a pdf so that we can redo it whenever the tutorial changes (which is frequently in initial development).

Adding print.css from https://github.com/rstudio/learnr/issues/465 to https://github.com/afrimapr/afrilearnr/tree/main/inst/tutorials/intro-to-spatial-r doesn't seem to work. 

From Chrome printing the hosted tutorial https://andysouth.shinyapps.io/intro-to-spatial-r to pdf just prints the first topic.

**Comment by andysouth** [comment]
in Chrome Ctrl Shift I gives developer tools that displays these warnings : 
![image](https://user-images.githubusercontent.com/3042629/114398782-14b9fe80-9b98-11eb-9f28-7b743406bd44.png)

**Comment by gadenbuie** [comment]
Maybe putting `print.css` in the `www/` directory will help?

**Comment by gadenbuie** [comment]
Also, the error is telling you that Chrome went looking for `print.css` but got back an HTML file instead. This typically happens when you look for a file and get a 404 page. Chrome wanted to get `print.css` from here https://andysouth.shinyapps.io/intro-to-spatial-r/print.css but the file isn't there (or isn't hosted by shinyapps.io there)

**Comment by andysouth** [comment]
Thankyou @gadenbuie it's helpful to know that chrome is failing to find the css file. I tried moving it to www/

& thankyou to @siebrenf I added the actionButton suggested https://github.com/rstudio/learnr/issues/465#issuecomment-817861943

However seemingly on shinyapps it is still failing to find print.css, although I did upload it to the server. It seems to be looking for it in a url that includes an extra code (session ID?). I've experimented with it in css/ or www/ folders.

This is where the css file is now : 
https://andysouth.shinyapps.io/intro-to-spatial-r/www/print.css
This is where chrome is looking for it & failing to find : 
https://andysouth.shinyapps.io/intro-to-spatial-r/_w_93feddc5/print.css

Running locally from the RStudio IDE the 'save to pdf' button seems to prompt no action.

Running the Rmd & selecting 'Open in Browser' the button does bring up the print dialog, but only offers to print the first Topic (i.e. 3 pages) instead of the whole tutorial. 

I would be happy with a solution that just works locally, or that works online.

**Comment by andysouth** [comment]
I did succeed in printing whole tutorials to pdf e.g. https://github.com/afrimapr/afrilearnr/blob/main/inst/pdfs/How%20to%20get%20your%20own%20spatial%20data%20into%20R%202021-04-23.pdf

But now its seems to have stopped working again !

The success happened after adding just the print css block 8869788626c63909aff60693a65a5888410735bc

Then Using RStudio, 'Run Document' locally to run just the one Rmd, followed by selecting 'Open in Browser', and Ctrl P from there.

HOWEVER after, Install & Restart, & running the tutorial from the tutorial tab this seems to have stopped working ??? it has gone back to printing just the single topic.

**Comment by andysouth** [comment]
Aha it stopped working because of a #comment I added in the css block. Taking it out and it is working again.

**Comment by andysouth** [comment]
This does allow printing whole tutorials from shinyapps too.

**Comment by andysouth** [comment]
Fixed by adding just the css block from rstudio/learnr#465 onto the end of the Rmd of each tutorial.

Note that both of these variations didn't work : 
1. I couldn't get the print.css file to work locally or on shinyapps - on shinyapps this was because it couldn't find the file
2. at one point I had a #comment in the css chunk, this caused it to fail i.e. printing from the browser just printed the single topic and gave no obvious error message
