### ISSUE TITLE
Online version of intro-to-spatial-r needs rgdal installed

### ISSUE THREAD

**Issue by anelda** [afrimapr/afrilearnr#17]
Hi Andy,

When running through https://andysouth.shinyapps.io/intro-to-spatial-r/ and getting to the last section (https://andysouth.shinyapps.io/intro-to-spatial-r/#section-h.-read-spatial-data-from-files), when clicking on `Run code` the following error comes up:

`Cannot create RasterLayer object from this file; perhaps you need to install rgdal first`

Same happens in Chrome and Firefox even when I click on `Start Over`

**Comment by AnneMTreasure** [comment]
Hi Andy and Anelda,

I'm getting the same error using Mac OS.

Cheers,
Anne

**Comment by andysouth** [comment]
Thanks @anelda @AnneMTreasure 

Should be fixed now :-) Is it OK for you ?

**Comment by anelda** [comment]
Thanks Andy, works for me now :-)

**Comment by AnneMTreasure** [comment]
yes, working for me too, thanks!
