### ISSUE TITLE
Installation of afrilearnr - no package called learnr

### ISSUE THREAD

**Issue by anelda** [afrimapr/afrilearnr#6]
I installed afrilearnr successfully and loaded the library, but when I run 

`learnr::run_tutorial("join-admin", "afrilearnr")
`
I get the following:

`Error in loadNamespace(name) : there is no package called ‘learnr’
`

**Comment by andysouth** [comment]
Thanks @anelda 

I have tried to fix with this commit : 828e451a121b3aef8121e5079aed2526a236405d

Can you try again ?

**Comment by anelda** [comment]
Thanks Andy! This works. I'll log the next error in a separate issue then you can close this one.
