### ISSUE TITLE
Tutorial tab in RStudio does not list all afrimapr tutorials

### ISSUE THREAD

**Issue by anelda** [afrimapr/afrilearnr#9]
Some random tutorials are listed and only the afrilearnr `get-my-data-in` is available from all the ones that are ready:
![image](https://user-images.githubusercontent.com/7215014/113886130-b8826380-97c0-11eb-92fe-908a8b5a6607.png)

![image](https://user-images.githubusercontent.com/7215014/113886204-c7691600-97c0-11eb-9fd9-70a5b4b0f5de.png)

This may be related to #8

**Comment by anelda** [comment]
May have to do with where afrilearnr thinks the base folder is? 

I get this when I try to run one of the other tutorials:

```
> learnr::run_tutorial("afrilearnr-crash-course", "afrilearnr")
Error: Tutorial "afrilearnr-crash-course" was not found in the "afrilearnr" package.
Available tutorials:
* afrilearnr
  - get-my-data-in     : "How to get your own spatial data into R"
  - openstreetmap-data : "Download and plot OpenStreetMap data from R"
  - template-tutorial  : "Blank afrimapr tutorial template"
  - test-tmap-view     : "test tmap failing in view mode when run by learner"
```

**Comment by andysouth** [comment]
Thanks :-) It seems that the earlier errors influence which tutorials become visible. So I think this issue is a symptom of the earlier ones. I'll look at them first.
